#!/usr/bin/env node
/**
 * Publishes the Creator Page background library (owner request, 30 Sep 2026; reference board
 * `docs/ui-redesign/boards/creator-page-backgrounds-2026-09-30.png`).
 *
 *   node scripts/creator-page-art/publish.mjs
 *
 * Every piece is vector art generated by `templates.mjs` / `decorations.mjs` from seeded randomness, so re-running
 * produces identical files. Each SVG is published under a content-hashed name. The five full backgrounds (and the wide
 * hero) also get AVIF + WebP renders at 430–1920w — their paint filters are costly to rasterise on phones — rendered in
 * Chromium so they match the SVG exactly. Writes the typed registry `packages/ui/src/brand/creator-page.ts`.
 */
import { createHash } from "node:crypto";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { chromium } from "playwright";
import { DECORATIONS, TEMPLATES, WIDE } from "./catalog.mjs";
import { TEMPLATE_PALETTES } from "./templates.mjs";

const root = new URL("../..", import.meta.url).pathname;
const sharp = createRequire(join(root, "apps/web/package.json"))("sharp");
const out = join(root, "apps/web/public/brand/creator-page");
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
const hash = (buf) => createHash("sha256").update(buf).digest("hex").slice(0, 10);
const WIDTHS = [430, 768, 1024, 1440, 1920];

function publishSvg(a) {
  const txt = a.make();
  if (/<script|\son[a-z]+=|javascript:|<foreignObject|href="http/i.test(txt)) throw new Error(`unsafe SVG: ${a.file}`);
  const buf = Buffer.from(txt);
  const name = `${a.file}.${hash(buf)}.svg`;
  writeFileSync(join(out, name), buf);
  const [, w, h] = /viewBox="0 0 (\d+) (\d+)"/.exec(txt);
  return { txt, svg: `/brand/creator-page/${name}`, width: Number(w), height: Number(h) };
}

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium" });
const page = await browser.newPage();
async function renderSet(a, v) {
  // Rendered without the grain layer: grain is what makes photos of paper heavy, so pages lay the tiny tileable
  // \`grainOverlay\` over the image instead (the SVG keeps its own grain).
  const plain = v.txt.replace(/<rect width="\d+" height="\d+" filter="url\(#grain\)"\/>/g, "");
  if (plain === v.txt) throw new Error(`no grain layer found in ${a.file}`);
  await page.setViewportSize({ width: v.width, height: v.height });
  await page.setContent(`<html><body style="margin:0"><img src="data:image/svg+xml;base64,${Buffer.from(plain).toString("base64")}" style="display:block;width:${v.width}px;height:${v.height}px"></body></html>`);
  await page.waitForTimeout(500);
  const png = await page.screenshot({ type: "png" });
  const avif = [], webp = [];
  for (const w of WIDTHS.filter((x) => x <= v.width)) {
    const img = sharp(png).resize({ width: w });
    const [av, wb] = await Promise.all([img.clone().avif({ quality: 52, effort: 6 }).toBuffer(), img.clone().webp({ quality: 78 }).toBuffer()]);
    const an = `${a.file}-${w}.${hash(av)}.avif`, wn = `${a.file}-${w}.${hash(wb)}.webp`;
    writeFileSync(join(out, an), av);
    writeFileSync(join(out, wn), wb);
    avif.push({ src: `/brand/creator-page/${an}`, width: w });
    webp.push({ src: `/brand/creator-page/${wn}`, width: w });
  }
  return { width: v.width, height: v.height, avif, webp };
}

const templates = {};
for (const a of [...TEMPLATES, ...WIDE]) {
  const v = publishSvg(a);
  templates[a.key] = { label: a.label, palette: TEMPLATE_PALETTES[a.key.replace(/Wide$/, "")], vector: { svg: v.svg, width: v.width, height: v.height }, image: await renderSet(a, v) };
  console.log(a.file);
}
const decorations = {};
for (const a of DECORATIONS) {
  const v = publishSvg(a);
  decorations[a.key] = { label: a.label, vector: { svg: v.svg, width: v.width, height: v.height } };
  console.log(a.file);
}
await browser.close();

const ts = `// Generated by scripts/creator-page-art/publish.mjs — do not edit by hand.
/**
 * The Creator Page background library (owner request, 30 Sep 2026): five template backgrounds and twelve supporting
 * decorations, authored as vector art at the owner's request from the reference board
 * \`docs/ui-redesign/boards/creator-page-backgrounds-2026-09-30.png\`. Each has its SVG (\`vector\`, for \`KitArt\`);
 * full backgrounds also carry AVIF/WebP renders (\`image\`) — prefer those for full-bleed use on phones.
 */
import type { BrandImageVariant } from "./watercolor";

export interface CreatorPageVector {
  svg: string;
  width: number;
  height: number;
}
export interface CreatorPageImage {
  width: number;
  height: number;
  avif: readonly BrandImageVariant[];
  webp: readonly BrandImageVariant[];
}

export const CREATOR_PAGE_TEMPLATES = ${JSON.stringify(templates, null, 2)} as const satisfies Record<string, { label: string; palette: readonly string[]; vector: CreatorPageVector; image: CreatorPageImage }>;

export const CREATOR_PAGE_DECORATIONS = ${JSON.stringify(decorations, null, 2)} as const satisfies Record<string, { label: string; vector: CreatorPageVector }>;

export type CreatorPageTemplate = keyof typeof CREATOR_PAGE_TEMPLATES;
export type CreatorPageDecoration = keyof typeof CREATOR_PAGE_DECORATIONS;
`;
writeFileSync(join(root, "packages/ui/src/brand/creator-page.ts"), ts);
console.log("registry written");
