// Generated by scripts/prepare-app-icons.mjs from the Vector Kit's app icon — full-bleed home-screen icons. Do not edit.
export const APP_ICONS = {
  "maskable512": {
    "src": "/brand/kit/app-icon-full-512.f72cee04d1.png",
    "width": 512,
    "height": 512
  },
  "maskable192": {
    "src": "/brand/kit/app-icon-full-192.4f59e78765.png",
    "width": 192,
    "height": 192
  },
  "apple180": {
    "src": "/brand/kit/app-icon-full-180.4147549d1b.png",
    "width": 180,
    "height": 180
  }
} as const;
