// Generated by scripts/creator-page-art/publish.mjs — do not edit by hand.
/**
 * The Creator Page background library (owner request, 30 Sep 2026): five template backgrounds and twelve supporting
 * decorations, authored as vector art at the owner's request from the reference board
 * `docs/ui-redesign/boards/creator-page-backgrounds-2026-09-30.png`. Each has its SVG (`vector`, for `KitArt`);
 * full backgrounds also carry AVIF/WebP renders (`image`) — prefer those for full-bleed use on phones.
 */
import type { BrandImageVariant } from "./watercolor";

export interface CreatorPageVector {
  svg: string;
  width: number;
  height: number;
}
export interface CreatorPageImage {
  width: number;
  height: number;
  avif: readonly BrandImageVariant[];
  webp: readonly BrandImageVariant[];
}

export const CREATOR_PAGE_TEMPLATES = {
  "immersiveHero": {
    "label": "Immersive Artistic Hero",
    "palette": [
      "#f5a988",
      "#e8b6c3",
      "#c9bde3",
      "#7682a8",
      "#2d2c3f"
    ],
    "vector": {
      "svg": "/brand/creator-page/immersive-hero.6aec2141b4.svg",
      "width": 1920,
      "height": 2560
    },
    "image": {
      "width": 1920,
      "height": 2560,
      "avif": [
        {
          "src": "/brand/creator-page/immersive-hero-430.ffceb14fbb.avif",
          "width": 430
        },
        {
          "src": "/brand/creator-page/immersive-hero-768.a36c617d77.avif",
          "width": 768
        },
        {
          "src": "/brand/creator-page/immersive-hero-1024.93e43a0d30.avif",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/immersive-hero-1440.a53185c6fb.avif",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/immersive-hero-1920.42c405c750.avif",
          "width": 1920
        }
      ],
      "webp": [
        {
          "src": "/brand/creator-page/immersive-hero-430.31cac6d6b5.webp",
          "width": 430
        },
        {
          "src": "/brand/creator-page/immersive-hero-768.a7a6110151.webp",
          "width": 768
        },
        {
          "src": "/brand/creator-page/immersive-hero-1024.ac9447fb28.webp",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/immersive-hero-1440.5664a1162b.webp",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/immersive-hero-1920.3a7679cef8.webp",
          "width": 1920
        }
      ]
    }
  },
  "editorialPaper": {
    "label": "Minimal Editorial Paper",
    "palette": [
      "#efe7da",
      "#dfcdb5",
      "#a3ae90",
      "#6f7d5d",
      "#8d7560"
    ],
    "vector": {
      "svg": "/brand/creator-page/editorial-paper.e92f68f20c.svg",
      "width": 1920,
      "height": 2560
    },
    "image": {
      "width": 1920,
      "height": 2560,
      "avif": [
        {
          "src": "/brand/creator-page/editorial-paper-430.9a151b5982.avif",
          "width": 430
        },
        {
          "src": "/brand/creator-page/editorial-paper-768.8e3812ed74.avif",
          "width": 768
        },
        {
          "src": "/brand/creator-page/editorial-paper-1024.c54ba97270.avif",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/editorial-paper-1440.f2bc950450.avif",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/editorial-paper-1920.4ae987db31.avif",
          "width": 1920
        }
      ],
      "webp": [
        {
          "src": "/brand/creator-page/editorial-paper-430.fd8a9ecbe4.webp",
          "width": 430
        },
        {
          "src": "/brand/creator-page/editorial-paper-768.b7237cb469.webp",
          "width": 768
        },
        {
          "src": "/brand/creator-page/editorial-paper-1024.de2073d3c9.webp",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/editorial-paper-1440.857aa65617.webp",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/editorial-paper-1920.0250392210.webp",
          "width": 1920
        }
      ]
    }
  },
  "cinematicDark": {
    "label": "Cinematic Dark",
    "palette": [
      "#14120f",
      "#2f4868",
      "#8a5a3c",
      "#e0a060",
      "#f3ebe0"
    ],
    "vector": {
      "svg": "/brand/creator-page/cinematic-dark.fd11bed47c.svg",
      "width": 1920,
      "height": 2560
    },
    "image": {
      "width": 1920,
      "height": 2560,
      "avif": [
        {
          "src": "/brand/creator-page/cinematic-dark-430.e40a072730.avif",
          "width": 430
        },
        {
          "src": "/brand/creator-page/cinematic-dark-768.af44f42e40.avif",
          "width": 768
        },
        {
          "src": "/brand/creator-page/cinematic-dark-1024.4f317b850f.avif",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/cinematic-dark-1440.332dbd6c0b.avif",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/cinematic-dark-1920.e83522a131.avif",
          "width": 1920
        }
      ],
      "webp": [
        {
          "src": "/brand/creator-page/cinematic-dark-430.55deb58f54.webp",
          "width": 430
        },
        {
          "src": "/brand/creator-page/cinematic-dark-768.c979bd661f.webp",
          "width": 768
        },
        {
          "src": "/brand/creator-page/cinematic-dark-1024.b9b11cf4bf.webp",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/cinematic-dark-1440.99cadfff22.webp",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/cinematic-dark-1920.e587bafb77.webp",
          "width": 1920
        }
      ]
    }
  },
  "creativeCollage": {
    "label": "Creative Collage",
    "palette": [
      "#d9bb92",
      "#e8ddcb",
      "#8f9a7c",
      "#8ea3bb",
      "#2f3d52"
    ],
    "vector": {
      "svg": "/brand/creator-page/creative-collage.dd4b7855f0.svg",
      "width": 1920,
      "height": 2560
    },
    "image": {
      "width": 1920,
      "height": 2560,
      "avif": [
        {
          "src": "/brand/creator-page/creative-collage-430.1fef9aca4f.avif",
          "width": 430
        },
        {
          "src": "/brand/creator-page/creative-collage-768.16c29088c3.avif",
          "width": 768
        },
        {
          "src": "/brand/creator-page/creative-collage-1024.0b5b2f6587.avif",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/creative-collage-1440.00dfa598d4.avif",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/creative-collage-1920.7a0ee4db7d.avif",
          "width": 1920
        }
      ],
      "webp": [
        {
          "src": "/brand/creator-page/creative-collage-430.c79aa12d81.webp",
          "width": 430
        },
        {
          "src": "/brand/creator-page/creative-collage-768.564a582470.webp",
          "width": 768
        },
        {
          "src": "/brand/creator-page/creative-collage-1024.9287266810.webp",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/creative-collage-1440.88399f0ade.webp",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/creative-collage-1920.16a88dd074.webp",
          "width": 1920
        }
      ]
    }
  },
  "softGradient": {
    "label": "Soft Gradient & Minimal",
    "palette": [
      "#c6bdf8",
      "#f8c7cf",
      "#c3d4fb",
      "#fbd7c3",
      "#f1ece8"
    ],
    "vector": {
      "svg": "/brand/creator-page/soft-gradient.dda1b0c731.svg",
      "width": 1920,
      "height": 2560
    },
    "image": {
      "width": 1920,
      "height": 2560,
      "avif": [
        {
          "src": "/brand/creator-page/soft-gradient-430.cd9009fa5b.avif",
          "width": 430
        },
        {
          "src": "/brand/creator-page/soft-gradient-768.60bd81259c.avif",
          "width": 768
        },
        {
          "src": "/brand/creator-page/soft-gradient-1024.ac11ac0de1.avif",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/soft-gradient-1440.6869387cb3.avif",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/soft-gradient-1920.272618d127.avif",
          "width": 1920
        }
      ],
      "webp": [
        {
          "src": "/brand/creator-page/soft-gradient-430.10aa63f3e5.webp",
          "width": 430
        },
        {
          "src": "/brand/creator-page/soft-gradient-768.4a9c629e91.webp",
          "width": 768
        },
        {
          "src": "/brand/creator-page/soft-gradient-1024.fc7cfcb9d1.webp",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/soft-gradient-1440.be4d49f4c8.webp",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/soft-gradient-1920.5fc13e5947.webp",
          "width": 1920
        }
      ]
    }
  },
  "immersiveHeroWide": {
    "label": "Immersive Artistic Hero (banner)",
    "palette": [
      "#f5a988",
      "#e8b6c3",
      "#c9bde3",
      "#7682a8",
      "#2d2c3f"
    ],
    "vector": {
      "svg": "/brand/creator-page/immersive-hero-wide.a778a070e6.svg",
      "width": 2880,
      "height": 1440
    },
    "image": {
      "width": 2880,
      "height": 1440,
      "avif": [
        {
          "src": "/brand/creator-page/immersive-hero-wide-430.aef5630ff8.avif",
          "width": 430
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-768.43f7f042e1.avif",
          "width": 768
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-1024.598c4a82d9.avif",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-1440.66db306d0a.avif",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-1920.b96d63d4e6.avif",
          "width": 1920
        }
      ],
      "webp": [
        {
          "src": "/brand/creator-page/immersive-hero-wide-430.6929dcc57f.webp",
          "width": 430
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-768.1da30758e7.webp",
          "width": 768
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-1024.f1a9e7c2ac.webp",
          "width": 1024
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-1440.9f38811e45.webp",
          "width": 1440
        },
        {
          "src": "/brand/creator-page/immersive-hero-wide-1920.b3d23124f8.webp",
          "width": 1920
        }
      ]
    }
  }
} as const satisfies Record<string, { label: string; palette: readonly string[]; vector: CreatorPageVector; image: CreatorPageImage }>;

export const CREATOR_PAGE_DECORATIONS = {
  "botanicalCorner": {
    "label": "Botanical Corner Cluster",
    "vector": {
      "svg": "/brand/creator-page/botanical-corner.afe8cf358e.svg",
      "width": 1600,
      "height": 1200
    }
  },
  "slimBranch": {
    "label": "Slim Branch Illustration",
    "vector": {
      "svg": "/brand/creator-page/slim-branch.3d1e0ed163.svg",
      "width": 1600,
      "height": 900
    }
  },
  "watercolorWash": {
    "label": "Watercolor Wash Blob",
    "vector": {
      "svg": "/brand/creator-page/watercolor-wash.1ee1175881.svg",
      "width": 1600,
      "height": 900
    }
  },
  "gradientBlob": {
    "label": "Translucent Gradient Blob",
    "vector": {
      "svg": "/brand/creator-page/gradient-blob.bd32b645fb.svg",
      "width": 1200,
      "height": 900
    }
  },
  "paperTape": {
    "label": "Paper Tape Pieces",
    "vector": {
      "svg": "/brand/creator-page/paper-tape.db7ab4549b.svg",
      "width": 1200,
      "height": 900
    }
  },
  "tornPaperStrip": {
    "label": "Torn Paper Strip",
    "vector": {
      "svg": "/brand/creator-page/torn-paper-strip.6d7668269e.svg",
      "width": 1600,
      "height": 600
    }
  },
  "inkScribble": {
    "label": "Ink Scribble Accents",
    "vector": {
      "svg": "/brand/creator-page/ink-scribble.959f8b7564.svg",
      "width": 1600,
      "height": 500
    }
  },
  "softShadowCard": {
    "label": "Soft Shadow Card Backdrop",
    "vector": {
      "svg": "/brand/creator-page/soft-shadow-card.a0a6eb75fa.svg",
      "width": 1600,
      "height": 900
    }
  },
  "grainOverlay": {
    "label": "Subtle Grain Overlay",
    "vector": {
      "svg": "/brand/creator-page/grain-overlay.827a8e7dbf.svg",
      "width": 512,
      "height": 512
    }
  },
  "lightLeak": {
    "label": "Light Leak / Glow Overlay",
    "vector": {
      "svg": "/brand/creator-page/light-leak.272738b489.svg",
      "width": 1600,
      "height": 900
    }
  },
  "cloudMist": {
    "label": "Cloud & Mist Overlay",
    "vector": {
      "svg": "/brand/creator-page/cloud-mist.c135a7258b.svg",
      "width": 1600,
      "height": 900
    }
  },
  "handwrittenNote": {
    "label": "Handwritten Note Element",
    "vector": {
      "svg": "/brand/creator-page/handwritten-note.45d5082a56.svg",
      "width": 1200,
      "height": 1100
    }
  }
} as const satisfies Record<string, { label: string; vector: CreatorPageVector }>;

export type CreatorPageTemplate = keyof typeof CREATOR_PAGE_TEMPLATES;
export type CreatorPageDecoration = keyof typeof CREATOR_PAGE_DECORATIONS;
