// Generated by scripts/prepare-brand-kit.mjs — do not edit by hand.
// Line icons from the owner-supplied Vector Kit; the only change is stroke → currentColor.
import * as React from "react";

type IconProps = Omit<React.SVGProps<SVGSVGElement>, "children"> & { size?: number | string };

function KitIcon({ size = 24, children, ...props }: IconProps & { children: React.ReactNode }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={1.6}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
      {...props}
    >
      {children}
    </svg>
  );
}

export function KitBookIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M12 7C10 5.3 7 4.7 3 5v13.8c4-.3 7 .3 9 2 2-1.7 5-2.3 9-2V5c-4-.3-7 .3-9 2Z" />
      <path d="M12 7v13.8" />
    </KitIcon>
  );
}

export function KitCameraIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M3.5 8.5a2 2 0 0 1 2-2h2.3L9.3 4h5.4l1.5 2.5h2.3a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2Z" />
      <circle cx="12" cy="13" r="3.6" />
    </KitIcon>
  );
}

export function KitFileIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M14 3.5H7A2 2 0 0 0 5 5.5v13a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8.5Z" />
      <path d="M14 3.5v5h5M9 13h6M9 16.5h6M9 9.5h2" />
    </KitIcon>
  );
}

export function KitHomeIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M3.5 10.2 12 3.5l8.5 6.7V19a1.5 1.5 0 0 1-1.5 1.5h-4.2V14.5H9.2v6H5A1.5 1.5 0 0 1 3.5 19Z" />
    </KitIcon>
  );
}

export function KitImageIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <rect x="3.5" y="3.5" width="17" height="17" rx="3" />
      <circle cx="9" cy="9" r="1.8" />
      <path d="m20.5 15-4.8-4.8L5 20.5" />
    </KitIcon>
  );
}

export function KitLayersIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="m12 3.5 8.5 4.5-8.5 4.5L3.5 8Z" />
      <path d="m3.5 12 8.5 4.5 8.5-4.5" />
      <path d="m3.5 16 8.5 4.5 8.5-4.5" />
    </KitIcon>
  );
}

export function KitLinkIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M10 14a4.2 4.2 0 0 0 6 0l3-3a4.2 4.2 0 0 0-6-6l-1.3 1.3" />
      <path d="M14 10a4.2 4.2 0 0 0-6 0l-3 3a4.2 4.2 0 0 0 6 6l1.3-1.3" />
    </KitIcon>
  );
}

export function KitMessageIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M5 4.5h14a2 2 0 0 1 2 2V15a2 2 0 0 1-2 2H9.5L5 20.5V17a2 2 0 0 1-2-2V6.5a2 2 0 0 1 2-2Z" />
      <circle cx="8" cy="10.8" r=".6" fill="#1E1B4B" />
      <circle cx="12" cy="10.8" r=".6" fill="#1E1B4B" />
      <circle cx="16" cy="10.8" r=".6" fill="#1E1B4B" />
    </KitIcon>
  );
}

export function KitMicIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <rect x="9" y="3" width="6" height="11.5" rx="3" />
      <path d="M5.5 11a6.5 6.5 0 0 0 13 0M12 17.5V21M9 21h6" />
    </KitIcon>
  );
}

export function KitPencilIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M15.8 4.2a2.2 2.2 0 0 1 3.1 0l.9.9a2.2 2.2 0 0 1 0 3.1L8.5 19.5 3.5 20.5l1-5Z" />
      <path d="m14 6 4 4" />
    </KitIcon>
  );
}

export function KitPlusIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M12 5v14M5 12h14" />
    </KitIcon>
  );
}

export function KitSearchIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <circle cx="11" cy="11" r="6.8" />
      <path d="m16 16 4.5 4.5" />
    </KitIcon>
  );
}

export function KitSettingsIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M20.60 12.00L20.53 13.12L20.31 14.23L18.37 14.64L17.98 15.45L17.47 16.20L18.08 18.08L17.24 18.82L16.30 19.45L14.64 18.37L13.79 18.66L12.90 18.84L12.00 20.60L10.88 20.53L9.77 20.31L9.36 18.37L8.55 17.98L7.80 17.47L5.92 18.08L5.18 17.24L4.55 16.30L5.63 14.64L5.34 13.79L5.16 12.90L3.40 12.00L3.47 10.88L3.69 9.77L5.63 9.36L6.02 8.55L6.53 7.80L5.92 5.92L6.76 5.18L7.70 4.55L9.36 5.63L10.21 5.34L11.10 5.16L12.00 3.40L13.12 3.47L14.23 3.69L14.64 5.63L15.45 6.02L16.20 6.53L18.08 5.92L18.82 6.76L19.45 7.70L18.37 9.36L18.66 10.21L18.84 11.10Z" />
      <circle cx="12" cy="12" r="2.8" />
    </KitIcon>
  );
}

export function KitSparklesIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M10.5 5.5C12.15 11.35 12.15 11.35 18.0 13C12.15 14.65 12.15 14.65 10.5 20.5C8.85 14.65 8.85 14.65 3.0 13C8.85 11.35 8.85 11.35 10.5 5.5Z" strokeLinejoin="round" />
      <path d="M18.5 2.7C19.116 4.884 19.116 4.884 21.3 5.5C19.116 6.116 19.116 6.116 18.5 8.3C17.884 6.116 17.884 6.116 15.7 5.5C17.884 4.884 17.884 4.884 18.5 2.7Z" strokeLinejoin="round" />
      <path d="M19 15.2C19.396 16.604 19.396 16.604 20.8 17C19.396 17.396 19.396 17.396 19 18.8C18.604 17.396 18.604 17.396 17.2 17C18.604 16.604 18.604 16.604 19 15.2Z" strokeLinejoin="round" />
    </KitIcon>
  );
}

export function KitTypeIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M5 7V4.5h14V7M12 4.5v15M9 19.5h6" />
    </KitIcon>
  );
}

export function KitUsersIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <circle cx="9" cy="8" r="3.5" />
      <path d="M2.8 20c0-3.6 2.8-6.2 6.2-6.2s6.2 2.6 6.2 6.2" />
      <circle cx="17" cy="8.6" r="2.6" />
      <path d="M17.2 13.9c2.4.3 4 2.3 4 5.1" />
    </KitIcon>
  );
}

export function KitVideoIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <rect x="2.5" y="6" width="13.5" height="12" rx="2.5" />
      <path d="M16 10.3 21.5 7v10L16 13.7" />
    </KitIcon>
  );
}

export function KitWaveformIcon(props: IconProps) {
  return (
    <KitIcon {...props}>
      <path d="M3 11v2M6 8.5v7M9 5v14M12 8v8M15 3.5v17M18 7.5v9M21 10.5v3" />
    </KitIcon>
  );
}
