// Generated by scripts/prepare-brand-kit.mjs — do not edit by hand.
// The owner-supplied Wonder Creator Vector Kit (see ASSETS.md). Files are content-hashed and served immutable.
import type { BrandImageVariant } from "./watercolor";

export interface KitVector {
  svg: string;
  width: number;
  height: number;
}
export interface KitRaster {
  width: number;
  height: number;
  avif: readonly BrandImageVariant[];
  webp: readonly BrandImageVariant[];
}
export type KitAsset = KitVector | KitRaster;

export const KIT = {
  logo: {
    logoFull: {
      svg: "/brand/kit/wonder-creator-logo-full.dd3fbf99a5.svg",
      width: 1090,
      height: 680,
    },
    logoMonoInk: {
      svg: "/brand/kit/wonder-creator-logo-mono-ink.6135570ccd.svg",
      width: 1090,
      height: 680,
    },
    logoNoTagline: {
      svg: "/brand/kit/wonder-creator-logo-no-tagline.a09981061e.svg",
      width: 1007,
      height: 420,
    },
    logoReversed: {
      svg: "/brand/kit/wonder-creator-logo-reversed.1465cc8f76.svg",
      width: 1090,
      height: 680,
    },
    logoStacked: {
      svg: "/brand/kit/wonder-creator-logo-stacked.bb2d187a66.svg",
      width: 667,
      height: 700,
    },
    symbolInk: {
      svg: "/brand/kit/wonder-creator-symbol-ink.e6b13d0fba.svg",
      width: 1024,
      height: 1024,
    },
    symbolWhite: {
      svg: "/brand/kit/wonder-creator-symbol-white.fe64d6d9cd.svg",
      width: 1024,
      height: 1024,
    },
    symbol: {
      svg: "/brand/kit/wonder-creator-symbol.04201cfe3b.svg",
      width: 1024,
      height: 1024,
    },
    tagline: {
      svg: "/brand/kit/wonder-creator-tagline.a40351ee90.svg",
      width: 1030,
      height: 340,
    },
  },
  appIcon: {
    appIconDark: {
      svg: "/brand/kit/app-icon-dark.c5e2322f9c.svg",
      width: 1024,
      height: 1024,
    },
    appIconLight: {
      svg: "/brand/kit/app-icon-light.8e11195631.svg",
      width: 1024,
      height: 1024,
    },
    appIconMono: {
      svg: "/brand/kit/app-icon-mono.3fc3f07e3e.svg",
      width: 1024,
      height: 1024,
    },
    appIconPrimary: {
      svg: "/brand/kit/app-icon-primary.e1b4ce4325.svg",
      width: 1024,
      height: 1024,
    },
  },
  paletteButton: {
    svg: "/brand/kit/palette-button-master.6320050f6b.svg",
    width: 512,
    height: 512,
  },
  appIconPng: {
    s512: {
      src: "/brand/kit/app-icon-primary-512.3cf1b53ac6.png",
      width: 512,
      height: 512,
    },
    s192: {
      src: "/brand/kit/app-icon-primary-192.13e002c5a4.png",
      width: 192,
      height: 192,
    },
    s180: {
      src: "/brand/kit/app-icon-primary-180.b783b7cfac.png",
      width: 180,
      height: 180,
    },
  },
  botanical: {
    botanicalSprig1: {
      width: 4000,
      height: 3954,
      avif: [
        {
          src: "/brand/kit/botanical-sprig-1-430.173cb6d29b.avif",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-1-768.0cf547a968.avif",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-1-1024.61a18397f2.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/botanical-sprig-1-430.a7afb3eb53.webp",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-1-768.7a46045940.webp",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-1-1024.7e55da47f2.webp",
          width: 1024,
        },
      ],
    },
    botanicalSprig2: {
      width: 3172,
      height: 4001,
      avif: [
        {
          src: "/brand/kit/botanical-sprig-2-430.f96ee8edc6.avif",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-2-768.8f5375cb7d.avif",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-2-1024.9135ff735c.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/botanical-sprig-2-430.fc84aeea69.webp",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-2-768.9ebd8bfe43.webp",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-2-1024.50ebcc31d0.webp",
          width: 1024,
        },
      ],
    },
    botanicalSprig3: {
      width: 3548,
      height: 4000,
      avif: [
        {
          src: "/brand/kit/botanical-sprig-3-430.3588832098.avif",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-3-768.8935ae34d7.avif",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-3-1024.eee4d0ad5a.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/botanical-sprig-3-430.ab783f14b0.webp",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-3-768.cd20503fdd.webp",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-3-1024.fe9a55d922.webp",
          width: 1024,
        },
      ],
    },
    botanicalSprig4: {
      width: 4000,
      height: 3929,
      avif: [
        {
          src: "/brand/kit/botanical-sprig-4-430.c4c43af198.avif",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-4-768.96cd924edb.avif",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-4-1024.480699e4b3.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/botanical-sprig-4-430.271bd0e5af.webp",
          width: 430,
        },
        {
          src: "/brand/kit/botanical-sprig-4-768.db11a839bf.webp",
          width: 768,
        },
        {
          src: "/brand/kit/botanical-sprig-4-1024.76e8aaf48f.webp",
          width: 1024,
        },
      ],
    },
  },
  wash: {
    washCream: {
      svg: "/brand/kit/wash-cream.3341444a80.svg",
      width: 2400,
      height: 2400,
    },
    washLavender: {
      svg: "/brand/kit/wash-lavender.89aa57bfea.svg",
      width: 2200,
      height: 3000,
    },
    washLilacSky: {
      svg: "/brand/kit/wash-lilac-sky.b5f5acf19f.svg",
      width: 2400,
      height: 2400,
    },
    washMint: {
      svg: "/brand/kit/wash-mint.8b4e578c7c.svg",
      width: 2400,
      height: 2400,
    },
    washPeach: {
      svg: "/brand/kit/wash-peach.457d96d2c9.svg",
      width: 3000,
      height: 2200,
    },
    washRose: {
      svg: "/brand/kit/wash-rose.88b8929704.svg",
      width: 2400,
      height: 2400,
    },
    washSage: {
      svg: "/brand/kit/wash-sage.200a39e842.svg",
      width: 2200,
      height: 3000,
    },
  },
  overlay: {
    gradientDawn4k: {
      svg: "/brand/kit/gradient-dawn-4k.ceb54c3672.svg",
      width: 3840,
      height: 2160,
    },
    gradientGoldenHour4k: {
      svg: "/brand/kit/gradient-golden-hour-4k.20845de13d.svg",
      width: 3840,
      height: 2160,
    },
    gradientLavenderMist4k: {
      svg: "/brand/kit/gradient-lavender-mist-4k.3637b5bfc4.svg",
      width: 3840,
      height: 2160,
    },
    overlayBlushOrb: {
      svg: "/brand/kit/overlay-blush-orb.2979dc716e.svg",
      width: 1600,
      height: 1600,
    },
    overlayIridescentSphere: {
      svg: "/brand/kit/overlay-iridescent-sphere.7fc1b575a2.svg",
      width: 1600,
      height: 1600,
    },
    overlayPastelArch: {
      svg: "/brand/kit/overlay-pastel-arch.c593ac3fdd.svg",
      width: 1200,
      height: 1600,
    },
    overlayPhotoTextScrim: {
      svg: "/brand/kit/overlay-photo-text-scrim.a76cd9b329.svg",
      width: 1290,
      height: 2796,
    },
    overlaySunsetOrb: {
      svg: "/brand/kit/overlay-sunset-orb.0f5e5838ef.svg",
      width: 1600,
      height: 1600,
    },
  },
  painted: {
    blossomSprig: {
      width: 2119,
      height: 3000,
      avif: [
        {
          src: "/brand/kit/blossom-sprig-430.c46d92ebad.avif",
          width: 430,
        },
        {
          src: "/brand/kit/blossom-sprig-768.6e8b924c1b.avif",
          width: 768,
        },
        {
          src: "/brand/kit/blossom-sprig-1024.925f22c061.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/blossom-sprig-430.aa54073bea.webp",
          width: 430,
        },
        {
          src: "/brand/kit/blossom-sprig-768.c370be19eb.webp",
          width: 768,
        },
        {
          src: "/brand/kit/blossom-sprig-1024.b8e6e68a0e.webp",
          width: 1024,
        },
      ],
    },
    coastalVignette: {
      width: 3000,
      height: 1286,
      avif: [
        {
          src: "/brand/kit/coastal-vignette-430.45be03852c.avif",
          width: 430,
        },
        {
          src: "/brand/kit/coastal-vignette-768.a46945a75b.avif",
          width: 768,
        },
        {
          src: "/brand/kit/coastal-vignette-1024.c459d4381d.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/coastal-vignette-430.5e23e9141f.webp",
          width: 430,
        },
        {
          src: "/brand/kit/coastal-vignette-768.8fd1d1c93d.webp",
          width: 768,
        },
        {
          src: "/brand/kit/coastal-vignette-1024.60e9b8ff54.webp",
          width: 1024,
        },
      ],
    },
    coralLeaves: {
      width: 2847,
      height: 3000,
      avif: [
        {
          src: "/brand/kit/coral-leaves-430.167b131017.avif",
          width: 430,
        },
        {
          src: "/brand/kit/coral-leaves-768.5785db38f4.avif",
          width: 768,
        },
        {
          src: "/brand/kit/coral-leaves-1024.65bf0edc6c.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/coral-leaves-430.dda74be434.webp",
          width: 430,
        },
        {
          src: "/brand/kit/coral-leaves-768.66d03123f5.webp",
          width: 768,
        },
        {
          src: "/brand/kit/coral-leaves-1024.b2714cca63.webp",
          width: 1024,
        },
      ],
    },
    flowerBranch: {
      width: 3000,
      height: 2637,
      avif: [
        {
          src: "/brand/kit/flower-branch-430.db8e97a5cd.avif",
          width: 430,
        },
        {
          src: "/brand/kit/flower-branch-768.1ca74fa7fc.avif",
          width: 768,
        },
        {
          src: "/brand/kit/flower-branch-1024.c95bdafd62.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/flower-branch-430.3a57313331.webp",
          width: 430,
        },
        {
          src: "/brand/kit/flower-branch-768.37139e401c.webp",
          width: 768,
        },
        {
          src: "/brand/kit/flower-branch-1024.b51d3fb4fe.webp",
          width: 1024,
        },
      ],
    },
    lavenderSprig: {
      width: 3000,
      height: 2719,
      avif: [
        {
          src: "/brand/kit/lavender-sprig-430.56b07a4a16.avif",
          width: 430,
        },
        {
          src: "/brand/kit/lavender-sprig-768.203658faf4.avif",
          width: 768,
        },
        {
          src: "/brand/kit/lavender-sprig-1024.6fd6fe3233.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/lavender-sprig-430.304dbf8562.webp",
          width: 430,
        },
        {
          src: "/brand/kit/lavender-sprig-768.fa616e80d6.webp",
          width: 768,
        },
        {
          src: "/brand/kit/lavender-sprig-1024.30ef978d3f.webp",
          width: 1024,
        },
      ],
    },
    leafSprigSage: {
      width: 3000,
      height: 2689,
      avif: [
        {
          src: "/brand/kit/leaf-sprig-sage-430.7b81dae211.avif",
          width: 430,
        },
        {
          src: "/brand/kit/leaf-sprig-sage-768.b66370e849.avif",
          width: 768,
        },
        {
          src: "/brand/kit/leaf-sprig-sage-1024.18ee96ed06.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/leaf-sprig-sage-430.7e3b3d8c68.webp",
          width: 430,
        },
        {
          src: "/brand/kit/leaf-sprig-sage-768.c85ccaaaea.webp",
          width: 768,
        },
        {
          src: "/brand/kit/leaf-sprig-sage-1024.3a3e727e45.webp",
          width: 1024,
        },
      ],
    },
  },
  mark: {
    birds: {
      svg: "/brand/kit/birds.2f27ae508d.svg",
      width: 800,
      height: 500,
    },
    blossomDots: {
      svg: "/brand/kit/blossom-dots.2346106768.svg",
      width: 800,
      height: 800,
    },
    confettiDots: {
      svg: "/brand/kit/confetti-dots.980feb425c.svg",
      width: 800,
      height: 800,
    },
    heartOutline: {
      svg: "/brand/kit/heart-outline.38d089c2b4.svg",
      width: 800,
      height: 800,
    },
    sparklePeach: {
      svg: "/brand/kit/sparkle-peach.5c6d215552.svg",
      width: 800,
      height: 800,
    },
    sparklePurple: {
      svg: "/brand/kit/sparkle-purple.d0525543b2.svg",
      width: 800,
      height: 800,
    },
    starGold: {
      svg: "/brand/kit/star-gold.62708bbedc.svg",
      width: 800,
      height: 800,
    },
    sun: {
      svg: "/brand/kit/sun.a195f2893a.svg",
      width: 800,
      height: 800,
    },
  },
  texture: {
    textureGrain: {
      svg: "/brand/kit/texture-grain.0d294fffa0.svg",
      width: 1024,
      height: 1024,
    },
    texturePaper: {
      svg: "/brand/kit/texture-paper.447196b65a.svg",
      width: 1024,
      height: 1024,
    },
    textureSoftShadow: {
      svg: "/brand/kit/texture-soft-shadow.f98daea93f.svg",
      width: 1024,
      height: 1024,
    },
    textureWatercolourPaper: {
      svg: "/brand/kit/texture-watercolour-paper.2d73e18ea6.svg",
      width: 1024,
      height: 1024,
    },
  },
  pattern: {
    patternSprigLavender: {
      width: 1046,
      height: 3998,
      avif: [
        {
          src: "/brand/kit/pattern-sprig-lavender-430.789cadea11.avif",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-sprig-lavender-768.963327c420.avif",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-sprig-lavender-1024.98edb37ef4.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/pattern-sprig-lavender-430.ca22f8f3d4.webp",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-sprig-lavender-768.41025441fe.webp",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-sprig-lavender-1024.a5070d11e9.webp",
          width: 1024,
        },
      ],
    },
    patternSprigPeach2: {
      width: 1333,
      height: 3999,
      avif: [
        {
          src: "/brand/kit/pattern-sprig-peach-2-430.49bf6bbc9c.avif",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-2-768.0e9cca11d4.avif",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-2-1024.82d536a4fc.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/pattern-sprig-peach-2-430.75c085cebe.webp",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-2-768.d6fdc70f4f.webp",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-2-1024.cf5ca5b6f0.webp",
          width: 1024,
        },
      ],
    },
    patternSprigPeach: {
      width: 1138,
      height: 4000,
      avif: [
        {
          src: "/brand/kit/pattern-sprig-peach-430.f186fd2568.avif",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-768.e2e1782f71.avif",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-1024.6480fd1bca.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/pattern-sprig-peach-430.0abaf166c5.webp",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-768.0aeb4ea82b.webp",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-sprig-peach-1024.bc325a55b4.webp",
          width: 1024,
        },
      ],
    },
    patternTileSeamlessOnCream: {
      width: 4000,
      height: 4000,
      avif: [
        {
          src: "/brand/kit/pattern-tile-seamless-on-cream-430.842a579a4a.avif",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-on-cream-768.0702382d36.avif",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-on-cream-1024.5d3d429735.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/pattern-tile-seamless-on-cream-430.c1c007f80c.webp",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-on-cream-768.4eed18a828.webp",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-on-cream-1024.a1ee02918b.webp",
          width: 1024,
        },
      ],
    },
    patternTileSeamless: {
      width: 4000,
      height: 4000,
      avif: [
        {
          src: "/brand/kit/pattern-tile-seamless-430.7a366a92a3.avif",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-768.8d24ccc349.avif",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-1024.8d0bafc5d4.avif",
          width: 1024,
        },
      ],
      webp: [
        {
          src: "/brand/kit/pattern-tile-seamless-430.86f68e4e21.webp",
          width: 430,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-768.89e2f8fdfd.webp",
          width: 768,
        },
        {
          src: "/brand/kit/pattern-tile-seamless-1024.2d31fd8978.webp",
          width: 1024,
        },
      ],
    },
  },
  iconChip: {
    book: {
      svg: "/brand/kit/icon-book-filled.06d9aa6412.svg",
      width: 64,
      height: 64,
    },
    camera: {
      svg: "/brand/kit/icon-camera-filled.72fb21ede2.svg",
      width: 64,
      height: 64,
    },
    file: {
      svg: "/brand/kit/icon-file-filled.445f55f2aa.svg",
      width: 64,
      height: 64,
    },
    home: {
      svg: "/brand/kit/icon-home-filled.170b21a6d1.svg",
      width: 64,
      height: 64,
    },
    image: {
      svg: "/brand/kit/icon-image-filled.c57efb2742.svg",
      width: 64,
      height: 64,
    },
    layers: {
      svg: "/brand/kit/icon-layers-filled.9e9403bab3.svg",
      width: 64,
      height: 64,
    },
    link: {
      svg: "/brand/kit/icon-link-filled.6f5fb1b616.svg",
      width: 64,
      height: 64,
    },
    message: {
      svg: "/brand/kit/icon-message-filled.c917736e67.svg",
      width: 64,
      height: 64,
    },
    mic: {
      svg: "/brand/kit/icon-mic-filled.a8c7aa2efe.svg",
      width: 64,
      height: 64,
    },
    pencil: {
      svg: "/brand/kit/icon-pencil-filled.68fde3cce9.svg",
      width: 64,
      height: 64,
    },
    plus: {
      svg: "/brand/kit/icon-plus-filled.cf5c00c7be.svg",
      width: 64,
      height: 64,
    },
    search: {
      svg: "/brand/kit/icon-search-filled.ed528b1e51.svg",
      width: 64,
      height: 64,
    },
    settings: {
      svg: "/brand/kit/icon-settings-filled.ddcc0d0e23.svg",
      width: 64,
      height: 64,
    },
    sparkles: {
      svg: "/brand/kit/icon-sparkles-filled.e307211f81.svg",
      width: 64,
      height: 64,
    },
    type: {
      svg: "/brand/kit/icon-type-filled.2c669577c7.svg",
      width: 64,
      height: 64,
    },
    users: {
      svg: "/brand/kit/icon-users-filled.7463abc258.svg",
      width: 64,
      height: 64,
    },
    video: {
      svg: "/brand/kit/icon-video-filled.de8b29776a.svg",
      width: 64,
      height: 64,
    },
    waveform: {
      svg: "/brand/kit/icon-waveform-filled.cf8d5fede1.svg",
      width: 64,
      height: 64,
    },
  },
} as const;
