// Generated by scripts/prepare-watercolor-assets.mjs — do not edit by hand.
// Owner-supplied watercolor artwork (see ASSETS.md). Files are content-hashed and served immutable.

export interface BrandImageVariant {
  src: string;
  width: number;
}

export interface BrandImage {
  /** Intrinsic size of the largest published rendition's source (trimmed original). */
  width: number;
  height: number;
  avif: readonly BrandImageVariant[];
  webp: readonly BrandImageVariant[];
}

export const WATERCOLOR = {
  paletteMotif: {
    width: 4546,
    height: 3970,
    avif: [
      {
        src: "/brand/watercolor/watercolor-paint-palette-96.2b620b50f4.avif",
        width: 96,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-144.2af57e75c9.avif",
        width: 144,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-192.1e2c9ccfbf.avif",
        width: 192,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-430.0de776cbad.avif",
        width: 430,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-768.3124570adf.avif",
        width: 768,
      },
    ],
    webp: [
      {
        src: "/brand/watercolor/watercolor-paint-palette-96.47f1d481c8.webp",
        width: 96,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-144.2f3c0d164d.webp",
        width: 144,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-192.d32bdb3381.webp",
        width: 192,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-430.0f6f2783d7.webp",
        width: 430,
      },
      {
        src: "/brand/watercolor/watercolor-paint-palette-768.a794205f79.webp",
        width: 768,
      },
    ],
  },
  cornerTopLeft: {
    width: 4946,
    height: 4878,
    avif: [
      {
        src: "/brand/watercolor/floral-corner-top-left-430.e58e89f318.avif",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-768.4572de6473.avif",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-1024.d7d08ebd4b.avif",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-1440.eea9c16add.avif",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-1920.d4988b4c2e.avif",
        width: 1920,
      },
    ],
    webp: [
      {
        src: "/brand/watercolor/floral-corner-top-left-430.e56c7bad08.webp",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-768.3057d0568c.webp",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-1024.31a8ba13e6.webp",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-1440.8d69455244.webp",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-top-left-1920.327d01ca43.webp",
        width: 1920,
      },
    ],
  },
  cornerTopRight: {
    width: 4198,
    height: 4888,
    avif: [
      {
        src: "/brand/watercolor/floral-corner-top-right-430.bfd56d5152.avif",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-768.0eba6e6e2d.avif",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-1024.3535bcfc43.avif",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-1440.49c19c9b06.avif",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-1920.20b9061580.avif",
        width: 1920,
      },
    ],
    webp: [
      {
        src: "/brand/watercolor/floral-corner-top-right-430.6d381fc776.webp",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-768.cbe2d0f62e.webp",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-1024.34107c4d82.webp",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-1440.108eb7460a.webp",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-top-right-1920.7699e25809.webp",
        width: 1920,
      },
    ],
  },
  cornerBottomLeft: {
    width: 4566,
    height: 4821,
    avif: [
      {
        src: "/brand/watercolor/floral-corner-bottom-left-430.94dcb709f2.avif",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-768.2a38c0d0b3.avif",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-1024.b0a6cba4a7.avif",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-1440.840c56627b.avif",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-1920.6183d8a6f7.avif",
        width: 1920,
      },
    ],
    webp: [
      {
        src: "/brand/watercolor/floral-corner-bottom-left-430.d675e587b2.webp",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-768.7b11abc1c4.webp",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-1024.7c9787a062.webp",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-1440.7cffd03685.webp",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-left-1920.fa671dad33.webp",
        width: 1920,
      },
    ],
  },
  cornerBottomRight: {
    width: 4709,
    height: 4921,
    avif: [
      {
        src: "/brand/watercolor/floral-corner-bottom-right-430.0a5c921124.avif",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-768.83f32f60a9.avif",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-1024.aec9661d11.avif",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-1440.da0b510f9d.avif",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-1920.5c5a09e55c.avif",
        width: 1920,
      },
    ],
    webp: [
      {
        src: "/brand/watercolor/floral-corner-bottom-right-430.894057f6a1.webp",
        width: 430,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-768.ed8546967e.webp",
        width: 768,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-1024.fa7376fa15.webp",
        width: 1024,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-1440.1f00d9719d.webp",
        width: 1440,
      },
      {
        src: "/brand/watercolor/floral-corner-bottom-right-1920.f4260aec75.webp",
        width: 1920,
      },
    ],
  },
  peachWash: {
    width: 4884,
    height: 3296,
    avif: [
      {
        src: "/brand/watercolor/watercolor-peach-wash-430.0144a9108e.avif",
        width: 430,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-768.6ca73f7c22.avif",
        width: 768,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-1024.b2e4d3cad6.avif",
        width: 1024,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-1440.31bb44632f.avif",
        width: 1440,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-1920.ea171d54c7.avif",
        width: 1920,
      },
    ],
    webp: [
      {
        src: "/brand/watercolor/watercolor-peach-wash-430.4966fcb77b.webp",
        width: 430,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-768.4e52c64852.webp",
        width: 768,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-1024.a240ae4ef5.webp",
        width: 1024,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-1440.c9eb56f6ba.webp",
        width: 1440,
      },
      {
        src: "/brand/watercolor/watercolor-peach-wash-1920.6c7d483f99.webp",
        width: 1920,
      },
    ],
  },
} as const satisfies Record<string, BrandImage>;

export type WatercolorKey = keyof typeof WATERCOLOR;
