import type { Track } from "./types";

/**
 * The Soundtrack library. Every track is licensed for use in the app and its license travels with it:
 * - Kevin MacLeod (incompetech.com), Creative Commons Attribution 4.0 — credited in the player's song details.
 * - Frédéric Chopin, recordings from Musopen's Complete Chopin Collection, CC0 (public domain).
 * Files are mirrored from `sourceUrl` into Wonder Creator storage by the server and checked against `sha256`.
 * Generated from verified downloads; edit with care (a changed file must change its hash).
 */
export const TRACKS: readonly Track[] = [
  {
    id: "kml-carefree",
    title: "Carefree",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["creative", "energy"],
    genre: "Ukulele pop",
    energy: "high",
    duration: 205,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Carefree” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carefree.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "8433b770a630d9b1594fd484442c677907ece899a4d149954cd2e74fd733e311",
    bytes: 6566713,
    instrumental: true,
  },
  {
    id: "kml-wallpaper",
    title: "Wallpaper",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["focus", "creative"],
    genre: "Electronic",
    energy: "medium",
    duration: 220,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Wallpaper” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wallpaper.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "9fa810e5193c88f1b360537366f210f16c2588106d5292f0659e9957fa274f96",
    bytes: 8804339,
    instrumental: true,
  },
  {
    id: "kml-local-forecast-elevator",
    title: "Local Forecast – Elevator",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["creative"],
    genre: "Lounge jazz",
    energy: "medium",
    duration: 189,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Local Forecast - Elevator” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Elevator.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "8c46b44e65324bc339fbbc3e770611d671f6c74a40f3ec8dd50332c082b25cc9",
    bytes: 7570404,
    instrumental: true,
  },
  {
    id: "kml-meditation-impromptu-01",
    title: "Meditation Impromptu 01",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["calm", "dreamy"],
    genre: "Ambient",
    energy: "low",
    duration: 213,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Meditation Impromptu 01” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Meditation%20Impromptu%2001.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "ac1332a12fe020cbeee206c7f33a82e29109d5ce63636e3302454e3bdfc36187",
    bytes: 7042622,
    instrumental: true,
  },
  {
    id: "kml-floating-cities",
    title: "Floating Cities",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["dreamy", "cinematic"],
    genre: "Ambient",
    energy: "medium",
    duration: 184,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Floating Cities” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Floating%20Cities.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "e7365652410d1fbc8a14d87537855d625c1a5fa8b7de8c626f47c13256ef2ddd",
    bytes: 5892113,
    instrumental: true,
  },
  {
    id: "kml-healing",
    title: "Healing",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["calm", "nature"],
    genre: "Ambient",
    energy: "low",
    duration: 520,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Healing” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Healing.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "7392a8a0b9c088d640e5c28f72d9f54a74cfa9344d41040e2058b998e3fc6987",
    bytes: 20805074,
    instrumental: true,
  },
  {
    id: "kml-dreamer",
    title: "Dreamer",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["dreamy", "calm"],
    genre: "Piano",
    energy: "low",
    duration: 204,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Dreamer” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dreamer.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "615e65c9ca131c11f8e12970644ed74ef822ec4f643b1d9d0085a223600bcdfb",
    bytes: 6532428,
    instrumental: true,
  },
  {
    id: "kml-deliberate-thought",
    title: "Deliberate Thought",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["focus"],
    genre: "Piano",
    energy: "low",
    duration: 177,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Deliberate Thought” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Deliberate%20Thought.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "243d5543c930bf54e95868bab9da860e67ce8835e3698881fda287bc58cc343f",
    bytes: 7224606,
    instrumental: true,
  },
  {
    id: "kml-easy-lemon",
    title: "Easy Lemon",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["creative", "energy"],
    genre: "Pop",
    energy: "medium",
    duration: 126,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Easy Lemon” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Easy%20Lemon.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "2486b8ecfe4575f9ab31613a2c03c2ee45e6e5280301d05b4dd7237c9e1c2531",
    bytes: 5057420,
    instrumental: true,
  },
  {
    id: "kml-clean-soul",
    title: "Clean Soul",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["focus", "calm"],
    genre: "Soft piano",
    energy: "low",
    duration: 307,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Clean Soul” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clean%20Soul.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "458868c225cf8f6dbaf17300aa2e0839386991be8581d0218554699297d7581c",
    bytes: 12271405,
    instrumental: true,
  },
  {
    id: "kml-heroic-age",
    title: "Heroic Age",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["cinematic", "energy"],
    genre: "Orchestral",
    energy: "high",
    duration: 97,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Heroic Age” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Heroic%20Age.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "d0bbd367ab8c6d744e18f317df12de67e1b40f8b5d1c3812d7025eec9e9a0e7b",
    bytes: 3902611,
    instrumental: true,
  },
  {
    id: "kml-enchanted-valley",
    title: "Enchanted Valley",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["nature", "dreamy"],
    genre: "Ambient",
    energy: "low",
    duration: 190,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Enchanted Valley” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Enchanted%20Valley.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "a8db733238ff78fb6a38f1ec802d52efe4cfb7487d4c5a63e50479a8df81eaf9",
    bytes: 7613259,
    instrumental: true,
  },
  {
    id: "kml-peaceful-desolation",
    title: "Peaceful Desolation",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["calm", "cinematic"],
    genre: "Orchestral",
    energy: "low",
    duration: 91,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Peaceful Desolation” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Peaceful%20Desolation.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "c9a233ef5956e409c433a9e1e0d62ff8c2ed873c7132c54c07067c73f5092ff7",
    bytes: 3648906,
    instrumental: true,
  },
  {
    id: "kml-frost-waltz",
    title: "Frost Waltz",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["dreamy", "cinematic"],
    genre: "Waltz",
    energy: "medium",
    duration: 135,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Frost Waltz” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Frost%20Waltz.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "560f932189551c8a009a671da25d8b51cf2067df85fcac35731ea6ac0c7d6cd3",
    bytes: 5526812,
    instrumental: true,
  },
  {
    id: "kml-porch-swing-days",
    title: "Porch Swing Days",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["nature", "calm"],
    genre: "Folk",
    energy: "low",
    duration: 216,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Porch Swing Days - slower” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Porch%20Swing%20Days%20-%20slower.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "f1d2c17ccbbee215561d5930343d8211f0bc34d2d8eee7125214cd2b028963ba",
    bytes: 8653643,
    instrumental: true,
  },
  {
    id: "kml-spring-thaw",
    title: "Spring Thaw",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["nature", "creative"],
    genre: "Acoustic",
    energy: "medium",
    duration: 54,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Spring Thaw” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Spring%20Thaw.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "aa5e9825628f2f6f4dd306609109aee3adb6a35849c6ab2b9ce5830c38c3663f",
    bytes: 2167035,
    instrumental: true,
  },
  {
    id: "kml-sovereign-quarter",
    title: "Sovereign Quarter",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["cinematic"],
    genre: "Orchestral",
    energy: "high",
    duration: 291,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Sovereign Quarter” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sovereign%20Quarter.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "d540076ae6e3aa9e74f40801c1adf9b081e423de9330ec3f8876d06f84820039",
    bytes: 11800135,
    instrumental: true,
  },
  {
    id: "kml-inspired",
    title: "Inspired",
    artist: "Kevin MacLeod",
    collection: "incompetech.com",
    moods: ["creative", "focus"],
    genre: "Piano",
    energy: "medium",
    duration: 286,
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "“Inspired” Kevin MacLeod (incompetech.com). Licensed under Creative Commons: By Attribution 4.0 License. http://creativecommons.org/licenses/by/4.0/",
    source: "incompetech.com",
    sourceUrl: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Inspired.mp3",
    infoUrl: "https://incompetech.com/music/royalty-free/music.html",
    sha256: "40b1af74145cedac77814d060155ad4658e04efa14d1b649decedc98fbb25f69",
    bytes: 9156393,
    instrumental: true,
  },
  {
    id: "chopin-nocturne-in-e-flat-op-9-no-2",
    title: "Nocturne in E-flat, Op. 9 No. 2",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["calm", "dreamy"],
    genre: "Classical piano",
    energy: "low",
    duration: 277,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Nocturne%20Op.%209%20no.%202%20in%20E%20flat%20major.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "d6a289cd51123f0033fb6e4014277495340c6d3afa3a4e42e7cd89bcf634d917",
    bytes: 5354496,
    instrumental: true,
  },
  {
    id: "chopin-nocturne-in-c-minor-op-48-no-1",
    title: "Nocturne in C minor, Op. 48 No. 1",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["cinematic", "calm"],
    genre: "Classical piano",
    energy: "medium",
    duration: 379,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Nocturne%20Op.%2048%20no.%201%20in%20C%20minor.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "d6ef702e05e24f91310562183c449d4b31df55b5cf7aa4c961ae72ac4966228c",
    bytes: 6243328,
    instrumental: true,
  },
  {
    id: "chopin-minute-waltz-op-64-no-1",
    title: "“Minute” Waltz, Op. 64 No. 1",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["energy", "creative"],
    genre: "Classical piano",
    energy: "high",
    duration: 107,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Waltz%20Op.%2064%20no.%201%20in%20D%20flat%20major.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "ed8f1a5354f3888dfad7e550f7672c973ed5799cc7815a4e8ee892d386b415b0",
    bytes: 2489344,
    instrumental: true,
  },
  {
    id: "chopin-waltz-in-c-sharp-minor-op-64-no-2",
    title: "Waltz in C-sharp minor, Op. 64 No. 2",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["dreamy", "focus"],
    genre: "Classical piano",
    energy: "medium",
    duration: 230,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Waltz%20Op.%2064%20no.%202%20in%20C%20sharp%20minor.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "201b20fc6bd5efe0b3e0cc890c2add5666df416433f1721e4a85ab41aafdc347",
    bytes: 5126656,
    instrumental: true,
  },
  {
    id: "chopin-farewell-waltz-op-69-no-1",
    title: "“Farewell” Waltz, Op. 69 No. 1",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["calm", "dreamy"],
    genre: "Classical piano",
    energy: "low",
    duration: 248,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Waltz%20Op.%2069%20no.%201%20in%20A%20flat%20major.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "97c83d792fcda82505214dc732cd3ab18698d89116d7704ce62dcfdeb182dcb9",
    bytes: 5426176,
    instrumental: true,
  },
  {
    id: "chopin-fantaisie-impromptu-op-66",
    title: "Fantaisie-Impromptu, Op. 66",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["energy", "cinematic"],
    genre: "Classical piano",
    energy: "high",
    duration: 327,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Fantasie%20Impromptu%20Op.%2066.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "8ec107d05c7420ba3f43651cff8139920de5d2a40aed8a6b50174ca4f1c1e6af",
    bytes: 6707200,
    instrumental: true,
  },
  {
    id: "chopin-raindrop-prelude-op-28-no-15",
    title: "“Raindrop” Prelude, Op. 28 No. 15",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["calm", "focus", "nature"],
    genre: "Classical piano",
    energy: "low",
    duration: 295,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Prelude%20Op.%2028%20no.%2015.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "25500f881fd4c9e1de5bd82f1c79a9e8b7b8f8ae574296db2c407ba706b0731e",
    bytes: 5668200,
    instrumental: true,
  },
  {
    id: "chopin-ballade-no-1-in-g-minor-op-23",
    title: "Ballade No. 1 in G minor, Op. 23",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["cinematic"],
    genre: "Classical piano",
    energy: "medium",
    duration: 614,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Ballade%20no.%201%20-%20Op.%2023.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "d9778293f57d99c368a83389b63815a4145105277ce9bb07c3773171aa0fff08",
    bytes: 12382720,
    instrumental: true,
  },
  {
    id: "chopin-grande-valse-brillante-op-18",
    title: "Grande Valse Brillante, Op. 18",
    artist: "Frédéric Chopin",
    collection: "Musopen — The Complete Chopin Collection",
    moods: ["energy", "creative"],
    genre: "Classical piano",
    energy: "high",
    duration: 319,
    license: "CC0 1.0 (public domain)",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Musopen (Internet Archive)",
    sourceUrl: "https://archive.org/download/musopen-chopin/Grande%20Valse%20Brilliante%20Op.18%20In%20E%20flat%20major.mp3",
    infoUrl: "https://archive.org/details/musopen-chopin",
    sha256: "c083df3613ddfaaee3a2bba902a33750e8a51fd63b22c8903587b31611e4d2dc",
    bytes: 6899712,
    instrumental: true,
  },
];
